### ISSUE TITLE
Hide cMenu window

### ISSUE THREAD

**Issue by iiz00** [chetachiezikeuzor/cMenu-Plugin#10]
Thank you for your very useful plugin!

Sometimes I want to hide cMenu window and see the whole background pane.
Is there any way to hide the window temporarily?
If not, please consider adding a command to toggle diplay/hide cMenu.

**Comment by chetachiezikeuzor** [comment]
Great idea! I was actually thinking about having a toggle in the status bar for easy access too. I should have this done pretty soon!

**Comment by chetachiezikeuzor** [comment]
Hello! The new update to cMenu add functionality for hiding cMenu. Please let me know if you have any issues.

![](https://raw.githubusercontent.com/chetachiezikeuzor/cMenu-Plugin/master/assets/cMenu%20status%20bar%20menu.gif)

**Comment by iiz00** [comment]
Thank you for the update!
It seems to work well, and adjusting window position is also useful.
I would be glad if you add this command for command palette so that we can assign a hotkey or cMenu button itself.

**Comment by chetachiezikeuzor** [comment]
Ok, the command will be added in the next release. Here's a quick demo (my hotkey is `cmd` + `Y`)

https://user-images.githubusercontent.com/79069364/132405260-5bff8c28-4d0a-4297-bdbd-a2cda8f56234.mp4

**Comment by chetachiezikeuzor** [comment]
The hide/show command has been added in the most [recent release](https://github.com/chetachiezikeuzor/cMenu-Plugin#112---sep-14-2021) 😊
