### ISSUE TITLE
Add tooltip for "remove last command" button in status menu

### ISSUE THREAD

**Issue by jsmorabito** [chetachiezikeuzor/cMenu-Plugin#16]
Since the cmenu doesn't update in real time (adding and removing commands) I had to check the check the update changelog to figure out what this button does

![image](https://user-images.githubusercontent.com/46250921/131261848-88899756-035c-41f5-b9af-460c69debd52.png)

**Comment by chetachiezikeuzor** [comment]
This will be in the next update!

**Comment by chetachiezikeuzor** [comment]
This has now been added! (Along with other features)
