### ISSUE TITLE
question or request

### ISSUE THREAD

**Issue by qzmtch** [chetachiezikeuzor/cMenu-Plugin#17]
is it possible to choose the number of items in the line? ![screen](https://i.imgur.com/wRsojbP.png) 
if not, you can add to the settings, the choice of the number of items in the line, i would like to see 15 in line

**Comment by chetachiezikeuzor** [comment]
Sure! I'll add this to my next update. Thanks!

**Comment by qzmtch** [comment]
plugin the best

**Comment by chetachiezikeuzor** [comment]
I added the new setting in the most [recent release](https://github.com/chetachiezikeuzor/cMenu-Plugin#112---sep-14-2021)!
