### ISSUE TITLE
[SUGGESTION] Use different icons for codeblock and inline-code

### ISSUE THREAD

**Issue by firinael** [chetachiezikeuzor/cMenu-Plugin#19]

**Comment by firinael** [comment]
There's these:

![image](https://user-images.githubusercontent.com/67032657/131750978-e6f8832b-9da3-49fd-b88d-41a9bab471f9.png)

Could use the codeblock one for blocks.

**Comment by chetachiezikeuzor** [comment]
🤢😣 But it's so ugly lmao

**Comment by chetachiezikeuzor** [comment]
Gah! I guess it's the only one that makes the most sense. Fine! 😤

**Comment by firinael** [comment]
https://icons8.com/icon/56934/code

how about one of these?

**Comment by chetachiezikeuzor** [comment]
Okay, I've changed the codeblock icon in the most [recent release](https://github.com/chetachiezikeuzor/cMenu-Plugin#112---sep-14-2021) 😊
