### ISSUE TITLE
Missing shortcut for **show / hide** toolbar

### ISSUE THREAD

**Issue by johans3** [chetachiezikeuzor/cMenu-Plugin#20]
cMenu places a nice  **hide and show**  popup in our status menu. 

My problem is, I prefer a shortcut over clickable icons, even if these icons and popups are nicely designed 
So i ask you kindly, if you could add the  **hide / show**  toggle to the list of shortcuts, that would be great awesome

**Comment by chetachiezikeuzor** [comment]
Sure! That'll be no problem. I'll go ahead and add in it the next release. Thanks!!

**Comment by chetachiezikeuzor** [comment]
https://user-images.githubusercontent.com/79069364/132222820-099a8124-2953-4069-9d2a-3613d40de43f.mp4

**Comment by chetachiezikeuzor** [comment]
Just added the shortcut in the [recent release](https://github.com/chetachiezikeuzor/cMenu-Plugin#112---sep-14-2021)!
