### ISSUE TITLE
Can I pull requests features? About remove tags.

### ISSUE THREAD

**Issue by AuTa** [chetachiezikeuzor/cMenu-Plugin#22]
I changed the applyCommand function. Now if there are corresponding prefix and suffix before and after the selected text, they can be removed.

The code is as follows:
https://github.com/AuTa/cMenu-Plugin/commit/67c8e4fb6033f8c1954b602c1347553d7192aeb2

Can I apply for a pull requests?

**Comment by chetachiezikeuzor** [comment]
Sure, the code looks lovely! Go ahead and submit the pull request, and I'll review it in a bit. Thanks for your contribution!
