### ISSUE TITLE
[FEATURE REQUEST]  cMenu for Preview mode

### ISSUE THREAD

**Issue by pathakraul** [chetachiezikeuzor/cMenu-Plugin#5]
Hi, this plugin is great and it will me more helpful if it can work in preview mode.

I am not sure if its even possible or not but wanted to check. If this works in preview mode then it will help in reviewing notes and highlighting.

**Comment by chetachiezikeuzor** [comment]
This is currently impossible to do. Preview mode has no editing functionality to tap into (at least not yet). We'll have to wait for the WYSIWYG feature to be released. Though, you can now add custom commands onto cMenu from the command palette.
