### ISSUE TITLE
cMenu append method set to body and not working

### ISSUE THREAD

**Issue by mathisgauthey** [chetachiezikeuzor/cMenu-Plugin#59]
Hi there, I tried using the cMenu append method to the body in order to use the sliding panes extension. But it doesn't change anything, it stays in the middle of the windows and doesn't follow the active pane, it must be broken. Tried with the classic theme and the Things3 one.

**Comment by mathisgauthey** [comment]
It seems like the commands are inverted, it works with the "workspace" selection. I can't seem to understand why, but it might helps.

**Comment by mathisgauthey** [comment]
Also, we can't change the height, hence the problem can't be solve by manually adjusting things.

**Comment by mathisgauthey** [comment]
Temporary solution to use with the Things3 appearance : 
- Setting *append method* to **workspace**.
- Changing this line **"cMenuBottomValue": 8,** in `.obsidian/plugins/cmenu-plugin/data.json`

**Comment by hustrjh** [comment]
Try this. [Obsidian-editing-toolbar](https://github.com/cumany/obsidian-editing-toolbar) :smile:
