### ISSUE TITLE
[SMALL BUG] Glass morphism doesn't apply on first launch

### ISSUE THREAD

**Issue by firinael** [chetachiezikeuzor/cMenu-Plugin#6]
Pretty simple, I had to (for some reason I can't fathom) enable the app and then disable it, then close and open the panes, in order to make the glass effect apply. The regular one worked fine as soon as I closed and opened the panes, but the glass one needed this workaround.

No idea why, might have something to do with it only appearing on pane refresh and some weird interaction with Sliding Panes?

Just reporting so it doesn't go unnoticed.

**Comment by chetachiezikeuzor** [comment]
That's strange. It's possible your theory may be right, I'll have to do some further testing to see what's going on.

**Comment by chetachiezikeuzor** [comment]
I've just tested with Sliding Panes and it works perfectly. Not quite sure what the issue is here but T=try uninstalling the plugin and reinstalling it.
