### ISSUE TITLE
[FEATURE REQUEST] Allow for customization with Style Settings

### ISSUE THREAD

**Issue by firinael** [chetachiezikeuzor/cMenu-Plugin#7]
The plugin's visuals didn't apply properly with my theme (no hover animations, and the text colour was white despite me using a light theme), and that'll probably happen with a ton of other themes, so it'd be nice to have an option to directly customize its visuals.

**Comment by chetachiezikeuzor** [comment]
I'm not sure what you mean by hover animations. The menu is a custom component so there shouldn't be any animation with it.  And I don't think it will be incompatible with other themes, so long as they're still using the basic variable from the Obsidian app css . I've tested with several themes and they were all just fine. I'm not sure why you're getting white text, as I have no css affecting global text color in the plugin css file. Could you elaborate on what's going on? What do you mean by white text?

**Comment by firinael** [comment]
I've posted a gfycat link on my other bug report, it shows that the bar's icons/text is white despite my default text colour being black.

Also I just thought it'd have some hover animations, it'd look great with some! Sorry for the mistake.

**Comment by chetachiezikeuzor** [comment]
Are you using Cidreira Coast theme?

**Comment by firinael** [comment]
I am... It's probably some issue with it being hacked-together a piece of crap, now that I think of it.
